### ISSUE TITLE
Add support for docker

### ISSUE THREAD

**Issue by benderillo** [etraxis/etraxis-abandoned#127]
Hi Artem,

I am trying to make eTraxis run in docker. Unsuccessfully so far...
The intent is to be able to publish images to docker hub that would be easy to run anywhere containers can run.
Pretty much like `redmine`: https://hub.docker.com/_/redmine 

If someone wants self-hosted eTraxis, the workflow for them would be as easy as:
1. Install docker
2. Run `docker pull etraxis:<release_version>` to get the image.
3. And run `docker run -d etraxis:latest --db-url <mysql access url>

Ideally, I want DB to be separated from the rest of eTraxis, so that we can provide a URL as runtime parameter (step 3) rather than having it installed and configured as part of eTraxis image itself.
But for now, I am struggling just to make it all run as it is.

I forked your repo and started writing the `Dockerfile` definition but stuck with MySQL integration.
You can have a look at what I have done so far: https://github.com/etraxis/etraxis/compare/master...benderillo:dockerise-launch

The `Dockerfile` is essentially set of instructions that defines the runtime environment.
I based mine off the `php` one that in turn is based on `alpine linux`. What it means is that I have php 7.1.29 installed and the base OS is alpine, then I add system components that must be installed for the rest of eTraxis to install. They are not documented in the Readme so I discovered them hard way.

I am currently stuck on running `composer install`. It fails on cache cleanup stage with the following error:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In AbstractMySQLDriver.php line 93:
!!                                                                                
!!    An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  
!!                                                                                
!!  
!!  In PDOConnection.php line 31:
!!                                               
!!    SQLSTATE[HY000] [2002] Connection refused  
!!                                               
!!  
!!  In PDOConnection.php line 27:
!!                                               
!!    SQLSTATE[HY000] [2002] Connection refused  
!!                                               
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```

I must say I have absolute 0 knowledge of PHP therefore have no clue what to do now.
I tired to define environment variables to point to mysql (copied it from your trevis/test config) but it didn't fix it.

Can you help me resolve current issue?
Also, what do you think about separating DB out of eTraxis and update it so it assumes that the DB is running separately and should be given rather at `run` step than `config/setup/install`?

**Comment by webinarium** [comment]
Hi Alexander,

Agreed about DB - it should be possible to connect the eTraxis docker instance to a database which runs on the master host, on the network, or even in another docker image.

Regarding issues you currently have. It can be solved, but there is one thing to consider - this version of eTraxis (4.x) is not completed yet, so it doesn't worth your effort. You may be looking for the older version (3.x), which can be downloaded from [here](https://github.com/etraxis/etraxis-obsolete).
